
#include "gs_srv_profile_interface_def.h"
#include "gs_srv_imageviewer_interface_def.h"
#include "gs_srv_idlescreen_interface_def.h"
#include "gs_srv_ebook_interface_def.h"
#include "gs_srv_videostream_interface_def.h"
#include "gs_srv_videorecord_interface_def.h"
#include "gs_srv_videopdl_interface_def.h"
#include "gs_srv_mmvideo_interface_def.h"
#include "gs_srv_bitstreamrecord_interface_def.h"
#include "gs_srv_bitstreamaudio_interface_def.h"
#include "gs_srv_ucm_interface_def.h"
#include "gs_srv_um_interface_def.h"
#include "gs_srv_mms_interface_def.h"
#include "gs_srv_email_interface_def.h"
#include "gs_srv_appmgr_interface_def.h"
//#include "gs_srv_ncenter_interface_def.h"
