<?xml version="1.0" encoding="UTF-8"?>

#include "MMI_features.h" 

<APP id="SRV_FILEMANAGER">
    <INCLUDE file="GlobalResDef.h"/>

<!-- 
**************************************** String section ***************************************
-->
<!-- FS Error -->
#ifdef __MMI_FILE_MANAGER__
#ifdef __MMI_SLIM_FILE_MANAGER__
    <STRING id="FMGR_FS_ABORTED_ERROR_TEXT"/>
    <STRING id="FMGR_FS_PATH_OVER_LEN_ERROR_TEXT"/>
    <STRING id="FMGR_FS_ROOT_DIR_FULL_TEXT"/>
    <STRING id="FMGR_FS_MEDIA_CHANGED_TEXT"/>
    <STRING id="FMGR_FS_FAT_ALLOC_ERROR_TEXT"/>
    <STRING id="FMGR_FS_WRITE_PROTECTION_TEXT"/>
    <STRING id="FMGR_FS_DRIVE_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_PARAM_ERROR_TEXT"/>
    <STRING id="FMGR_FS_FILE_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_ACCESS_DENIED_TEXT"/>
    <STRING id="FMGR_FS_PATH_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_DEVICE_BUSY_TEXT"/>
    <STRING id="FMGR_FS_APP_QUOTA_FULL_TEXT"/>
#else
    <STRING id="FMGR_FS_PARAM_ERROR_TEXT"/>
    <STRING id="FMGR_FS_DRIVE_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_TOO_MANY_FILES_TEXT"/>
    <STRING id="FMGR_FS_NO_MORE_FILES_TEXT"/>
    <STRING id="FMGR_FS_WRONG_MEDIA_TEXT"/>
    <STRING id="FMGR_FS_INVALID_FILE_SYSTEM_TEXT"/>
    <STRING id="FMGR_FS_FILE_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_INVALID_FILE_HANDLE_TEXT"/>
    <STRING id="FMGR_FS_UNSUPPORTED_DEVICE_TEXT"/>
    <STRING id="FMGR_FS_UNSUPPORTED_DRIVER_FUNCTION_TEXT"/>
    <STRING id="FMGR_FS_CORRUPTED_PARTITION_TABLE_TEXT"/>
    <STRING id="FMGR_FS_TOO_MANY_DRIVES_TEXT"/>
    <STRING id="FMGR_FS_INVALID_FILE_POS_TEXT"/>
    <STRING id="FMGR_FS_ACCESS_DENIED_TEXT"/>
    <STRING id="FMGR_FS_STRING_BUFFER_TOO_SMALL_TEXT"/>
    <STRING id="FMGR_FS_GENERAL_FAILURE_TEXT"/>
    <STRING id="FMGR_FS_PATH_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_FAT_ALLOC_ERROR_TEXT"/>
    <STRING id="FMGR_FS_ROOT_DIR_FULL_TEXT"/>
    <STRING id="FMGR_FS_TIMEOUT_TEXT"/>
    <STRING id="FMGR_FS_BAD_SECTOR_TEXT"/>
    <STRING id="FMGR_FS_DATA_ERROR_TEXT"/>
    <STRING id="FMGR_FS_MEDIA_CHANGED_TEXT"/>
    <STRING id="FMGR_FS_SECTOR_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_ADDRESS_MARK_NOT_FOUND_TEXT"/>
    <STRING id="FMGR_FS_DRIVE_NOT_READY_TEXT"/>
    <STRING id="FMGR_FS_WRITE_PROTECTION_TEXT"/>
    <STRING id="FMGR_FS_DMA_OVERRUN_TEXT"/>
    <STRING id="FMGR_FS_CRC_ERROR_TEXT"/>
    <STRING id="FMGR_FS_DEVICE_RESOURCE_ERROR_TEXT"/>
    <STRING id="FMGR_FS_INVALID_SECTOR_SIZE_TEXT"/>
    <STRING id="FMGR_FS_OUT_OF_BUFFERS_TEXT"/>
    <STRING id="FMGR_FS_FILE_EXISTS_TEXT"/>
    <STRING id="FMGR_FS_LONG_FILE_POS_TEXT"/>
    <STRING id="FMGR_FS_FILE_TOO_LARGE_TEXT"/>
    <STRING id="FMGR_FS_BAD_DIR_ENTRY_TEXT"/>
    <STRING id="FMGR_FS_READ_ONLY_ERROR_TEXT"/>
    <STRING id="FMGR_FS_SYSTEM_CRASH_TEXT"/>
    <STRING id="FMGR_FS_DEVICE_BUSY_TEXT"/>
    <STRING id="FMGR_FS_ABORTED_ERROR_TEXT"/>
    <STRING id="FMGR_FS_FLASH_MOUNT_ERROR_TEXT"/>
    <STRING id="FMGR_FS_PATH_OVER_LEN_ERROR_TEXT"/>
    <STRING id="FMGR_FS_APP_QUOTA_FULL_TEXT"/>
    <STRING id="FMGR_FS_DEVICE_EXPORTED_ERROR_TEXT"/>
    <STRING id="FMGR_FS_MSDC_MOUNT_ERROR_TEXT"/>
    <STRING id="FMGR_FS_MSDC_READ_SECTOR_ERROR_TEXT"/>
    <STRING id="FMGR_FS_MSDC_WRITE_SECTOR_ERROR_TEXT"/>
    <STRING id="FMGR_FS_MSDC_DISCARD_SECTOR_ERROR_TEXT"/>
    <STRING id="FMGR_FS_MSDC_PRESENT_NOT_READY_TEXT"/>
    <STRING id="FMGR_FS_MSDC_NOT_PRESENT_TEXT"/>
    <STRING id="FMGR_FS_FLASH_ERASE_BUSY_TEXT"/>
    <STRING id="FMGR_FS_LOCK_MUTEX_FAIL_TEXT"/>
#endif
<!-- Storage name -->
#if defined (__FS_CARD2_SUPPORT__)
    <STRING id="STR_ID_FMGR_MEMORY_CARD2"/>
#endif
#ifdef __SIM_PLUS__
    <STRING id="STR_FMGR_SIM_PLUS"/>
    <STRING id="STR_FMGR_SIM_PLUS2"/>
    <STRING id="STR_FMGR_SIM_PLUS3"/>
    <STRING id="STR_FMGR_SIM_PLUS4"/>
#endif
#ifdef __OTG_ENABLE__
    <STRING id="STR_FMGR_USB_STORAGE"/>
    <STRING id="STR_FMGR_USB_STORAGE2"/>
    <STRING id="STR_FMGR_USB_STORAGE3"/>
    <STRING id="STR_FMGR_USB_STORAGE4"/>
    <STRING id="STR_FMGR_USB_STORAGE5"/>
    <STRING id="STR_FMGR_USB_STORAGE6"/>
    <STRING id="STR_FMGR_USB_STORAGE7"/>
    <STRING id="STR_FMGR_USB_STORAGE8"/>
#endif

#if defined(__MMI_FMGR_SUPPORT_DEFAULT_STORAGE__)
    <STRING id="STR_ID_FMGR_CARD_APPLY_DEF_STORAGE"/>
    <STRING id="STR_ID_FMGR_CARD_APPLY_DEF_STORAGE2"/>
    <STRING id="STR_ID_FMGR_CARD_APPLY_DEF_STORAGE3"/>
#endif
#if defined(__MMI_FMGR_SUPPORT_SOFT_UNMOUNT__) && !defined(__MMI_SLIM_FILE_MANAGER__)
    <STRING id="STR_ID_FMGR_CARD_REMOVE_PROMPT"/>
    #ifdef __OTG_ENABLE__
    <STRING id="STR_ID_FMGR_OTG_REMOVE_PROMPT"/>
    #endif
#endif
#ifdef __OTG_ENABLE__
    <STRING id="STR_FMGR_OTG_UNSUPPORT"/>
    <STRING id="STR_FMGR_OTG_CONNECTING"/>
    <STRING id="STR_FMGR_OTG_STOP_CONNECTING"/>
    <STRING id="STR_FMGR_OTG_NO_RESPONSE"/>
    <STRING id="STR_FMGR_OTG_HNP_PROCESS"/>
    <STRING id="STR_FMGR_OTG_HNP_STOP"/>
    <STRING id="STR_FMGR_OTG_HUB_NOT_SUPPORT"/>
    <STRING id="STR_FMGR_OTG_UNSUPPORT_CABLE"/>
#endif

    <STRING id="STR_FMGR_CARD_MOUNTING"/>
    
    <!-- Event registration -->
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_ADV_ACTION"       hfile="FileMgrSrvGProt.h" />
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_IN"      hfile="FileMgrSrvGProt.h" />
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_OUT"     hfile="FileMgrSrvGProt.h" />
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_SOFT_MOUNT"   hfile="FileMgrSrvGProt.h" />
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_READY"        hfile="FileMgrSrvGProt.h" />
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_FORMAT"           hfile="FileMgrSrvGProt.h" />
	<SENDER id="EVT_ID_SRV_FMGR_NOTIFICATION_SET_DEF_STORAGE"  hfile="FileMgrSrvGProt.h" />

	<SENDER id="EVT_ID_SRV_FMGRI_CARD_PLUG_IN"                 hfile="FileMgrSrvIProt.h" />
	<SENDER id="EVT_ID_SRV_FMGRI_CARD_PLUG_OUT"                hfile="FileMgrSrvIProt.h" />
	<SENDER id="EVT_ID_SRV_FMGRI_CARD_DISPLAY_MOUNTING"        hfile="FileMgrSrvIProt.h" />

#ifdef __MMI_FMGR_CUSTICON_SUPPORT__
	<RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_FORMAT"         proc="srv_fmgr_cidb_notify_hdlr" />
    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_ADV_ACTION"     proc="srv_fmgr_cidb_notify_hdlr" />
#endif
    <RECEIVER id="EVT_ID_USB_ENTER_MS_MODE"                    proc="srv_fmgr_ms_handler" />
    <RECEIVER id="EVT_ID_USB_EXIT_MS_MODE"                     proc="srv_fmgr_ms_handler" />

    <!-- NVRAM related -->
    <CACHEDATA type="byte" id="NVRAM_EF_FMGR_SORT_OPTION_LID" restore_flag="TRUE">
        <DEFAULT_VALUE> [0xFF] </DEFAULT_VALUE>
        <DESCRIPTION> Byte Cache </DESCRIPTION>
    </CACHEDATA>
#endif
</APP>
