/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   SSCResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for SSC resource definitions
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __SSC_RES_DEF_H__
#define __SSC_RES_DEF_H__

#include "MMIDataType.h"    /* for resource base */

/* auto add by kw_check begin */
#include "mmi_res_range_def.h"
/* auto add by kw_check end */

/***************************************************************************** 
 * Typedef for Resource Enum
 *****************************************************************************/
/* Screen IDs */
typedef enum
{
    SCR_ENTER_SSC = IDLE_APP_BASE + 550,
    SCR_ENTER_SW_VERSION,
    SCR_ENTER_HW_VERSION,
    SCR_ENTER_SERIAL_NUMBER
} SSC_SCR_ID_ENUM;

/* String IDs */
typedef enum
{
    SSC_SCR_LANGUAGE_ENGLISH_STR_ID = IDLE_APP_BASE + 550,
    SSC_SCR_LANGUAGE_SCHINESE_STR_ID,
    SSC_SCR_LANGUAGE_TCHINESE_STR_ID,
    SSC_SCR_LANGUAGE_DEFAULT_STR_ID,
    SSC_SCR_LANGUAGE_SPANISH_STR_ID,
    SSC_SCR_LANGUAGE_DANISH_STR_ID,
    SSC_SCR_LANGUAGE_POLISH_STR_ID,
    SSC_SCR_LANGUAGE_FRENCH_STR_ID,
    SSC_SCR_LANGUAGE_GERMAN_STR_ID,
    SSC_SCR_LANGUAGE_ITALIAN_STR_ID,
    SSC_SCR_LANGUAGE_AZERBAIJANI_STR_ID,
    SSC_SCR_LANGUAGE_CATALAN_STR_ID,
    SSC_SCR_LANGUAGE_KAZAKH_STR_ID,
    SSC_SCR_LANGUAGE_MACEDONIAN_STR_ID,
    SSC_SCR_LANGUAGE_SA_PORTUGUESE_STR_ID,
    SSC_SCR_LANGUAGE_CA_FRENCH_STR_ID,
    SSC_SCR_LANGUAGE_HK_CHINESE_STR_ID,
    SSC_SCR_LANGUAGE_UK_ENGLISH_STR_ID,
    SSC_SCR_LANGUAGE_SA_SPANISH_STR_ID,
    SSC_SCR_LANGUAGE_ICELANDIC_STR_ID,
    SSC_SCR_LANGUAGE_SERBIAN_STR_ID,
    SSC_SCR_LANGUAGE_YORUBA_STR_ID,
    SSC_SCR_LANGUAGE_HAUSA_STR_ID,
    SSC_SCR_LANGUAGE_GALICIAN_STR_ID,
    SSC_SCR_LANGUAGE_BASQUE_STR_ID,
    SSC_SCR_LANGUAGE_IGBO_STR_ID,
    SSC_SCR_LANGUAGE_FILIPINO_STR_ID,
    SSC_SCR_LANGUAGE_IRISH_STR_ID,
    SSC_SCR_LANGUAGE_KOREAN_STR_ID,
    SSC_SCR_LANGUAGE_SESOTHO_STR_ID,
    SSC_SCR_LANGUAGE_TAGALOG_STR_ID,
    SSC_SCR_LANGUAGE_THAI_STR_ID,
    SSC_SCR_LANGUAGE_RUSSIAN_STR_ID,
    SSC_SCR_LANGUAGE_BULGARIAN_STR_ID,
    SSC_SCR_LANGUAGE_UKRAINIAN_STR_ID,
    SSC_SCR_LANGUAGE_PORTUGUESE_STR_ID,
    SSC_SCR_LANGUAGE_TURKISH_STR_ID,
    SSC_SCR_LANGUAGE_VIETNAMESE_STR_ID,
    SSC_SCR_LANGUAGE_INDONESIAN_STR_ID,
    SSC_SCR_LANGUAGE_CZECH_STR_ID,
    SSC_SCR_LANGUAGE_MALAY_STR_ID,
    SSC_SCR_LANGUAGE_FINNISH_STR_ID,
    SSC_SCR_LANGUAGE_HUNGARIAN_STR_ID,
    SSC_SCR_LANGUAGE_SLOVAK_STR_ID,
    SSC_SCR_LANGUAGE_DUTCH_STR_ID,
    SSC_SCR_LANGUAGE_NORWEGIAN_STR_ID,
    SSC_SCR_LANGUAGE_SWEDISH_STR_ID,
    SSC_SCR_LANGUAGE_CROATIAN_STR_ID,
    SSC_SCR_LANGUAGE_ROMANIAN_STR_ID,
    SSC_SCR_LANGUAGE_SLOVENIAN_STR_ID,
    SSC_SCR_LANGUAGE_GREEK_STR_ID,
    SSC_SCR_LANGUAGE_HEBREW_STR_ID,
    SSC_SCR_LANGUAGE_ARABIC_STR_ID,
    SSC_SCR_LANGUAGE_PERSIAN_STR_ID,
    SSC_SCR_LANGUAGE_URDU_STR_ID,
    SSC_SCR_LANGUAGE_HINDI_STR_ID,
    SSC_SCR_LANGUAGE_TAMIL_STR_ID,
    SSC_SCR_LANGUAGE_BENGALI_STR_ID,
    SSC_SCR_LANGUAGE_ASSAMESE_STR_ID,
    SSC_SCR_LANGUAGE_MARATHI_STR_ID,
    SSC_SCR_LANGUAGE_PUNJABI_STR_ID,
    SSC_SCR_LANGUAGE_TELUGU_STR_ID,
    SSC_SCR_LANGUAGE_XHOSA_STR_ID,       
    SSC_SCR_LANGUAGE_SWAHILI_STR_ID,   
    SSC_SCR_LANGUAGE_AFRIKAANS_STR_ID,  
    SSC_SCR_LANGUAGE_ZULU_STR_ID,   
    SSC_SCR_LANGUAGE_LITHUANIAN_STR_ID,   
    SSC_SCR_LANGUAGE_LATVIAN_STR_ID,   
    SSC_SCR_LANGUAGE_ESTONIAN_STR_ID, 
    SSC_SCR_LANGUAGE_ARMENIAN_STR_ID,   
    SSC_SCR_LANGUAGE_ALBANIAN_STR_ID,
    SSC_SCR_LANGUAGE_GEORGIAN_STR_ID,   
    SSC_SCR_LANGUAGE_MOLDOVAN_STR_ID,     
    SSC_SCR_LANGUAGE_KANNADA_STR_ID,
    SSC_SCR_LANGUAGE_MALAYALAM_STR_ID,
    SSC_SCR_LANGUAGE_LAO_STR_ID,
    SSC_SCR_LANGUAGE_KHMER_STR_ID,
    SSC_SCR_LANGUAGE_MYANMAR_STR_ID,
    SSC_SCR_LANGUAGE_GUJARATI_STR_ID,
    SSC_SCR_LANGUAGE_ORIYA_STR_ID,
    SSC_SCR_LANGUAGE_ZAWGYI_STR_ID,
    SSC_STR_ERR_SET_SCHINESE,
    SSC_STR_ERR_SET_TCHINESE,
    SSC_STR_ERR_SET_SPANISH,
    SSC_STR_ERR_SET_DANISH,
    SSC_STR_ERR_SET_POLISH,
    SSC_STR_ERR_SET_FRENCH,
    SSC_STR_ERR_SET_GERMAN,
    SSC_STR_ERR_SET_AZERBAIJANI,
    SSC_STR_ERR_SET_KOREAN,
    SSC_STR_ERR_SET_CATALAN,
    SSC_STR_ERR_SET_KAZAKH	,
    SSC_STR_ERR_SET_MACEDONIAN,
    SSC_STR_ERR_SET_SA_PORTUGUESE,
    SSC_STR_ERR_SET_CA_FRENCH,
    SSC_STR_ERR_SET_HK_CHINESE	,
    SSC_STR_ERR_SET_UK_ENGLISH,
    SSC_STR_ERR_SET_SA_SPANISH,
    SSC_STR_ERR_SET_ICELANDIC,
    SSC_STR_ERR_SET_SERBIAN,
    SSC_STR_ERR_SET_YORUBA,
    SSC_STR_ERR_SET_HAUSA,
    SSC_STR_ERR_SET_SESOTHO,
    SSC_STR_ERR_SET_TAGALOG,
    SSC_STR_ERR_SET_GALICIAN,
    SSC_STR_ERR_SET_BASQUE,
    SSC_STR_ERR_SET_IGBO,
    SSC_STR_ERR_SET_FILIPINO,
    SSC_STR_ERR_SET_IRISH,
    SSC_STR_ERR_SET_ITALIAN,
    SSC_STR_ERR_SET_THAI,
    SSC_STR_ERR_SET_RUSSIAN,
    SSC_STR_ERR_SET_BULGARIAN,
    SSC_STR_ERR_SET_UKRAINIAN,
    SSC_STR_ERR_SET_PORTUGUESE,
    SSC_STR_ERR_SET_TURKISH,
    SSC_STR_ERR_SET_VIETNAMESE,
    SSC_STR_ERR_SET_INDONESIAN,
    SSC_STR_ERR_SET_CZECH,
    SSC_STR_ERR_SET_MALAY,
    SSC_STR_ERR_SET_FINNISH,
    SSC_STR_ERR_SET_HUNGARIAN,
    SSC_STR_ERR_SET_SLOVAK,
    SSC_STR_ERR_SET_DUTCH,
    SSC_STR_ERR_SET_NORWEGIAN,
    SSC_STR_ERR_SET_SWEDISH,
    SSC_STR_ERR_SET_CROATIAN,
    SSC_STR_ERR_SET_ROMANIAN,
    SSC_STR_ERR_SET_SLOVENIAN,
    SSC_STR_ERR_SET_GREEK,
    SSC_STR_ERR_SET_HEBREW,
    SSC_STR_ERR_SET_ARABIC,
    SSC_STR_ERR_SET_PERSIAN,
    SSC_STR_ERR_SET_URDU,
    SSC_STR_ERR_SET_HINDI,
    SSC_STR_ERR_SET_TAMIL,
    SSC_STR_ERR_SET_BENGALI,
    SSC_STR_ERR_SET_ASSAMESE,
    SSC_STR_ERR_SET_MARATHI,
    SSC_STR_ERR_SET_PUNJABI,
    SSC_STR_ERR_SET_TELUGU,
    SSC_STR_ERR_SET_XHOSA,     
    SSC_STR_ERR_SET_SWAHILI,      
    SSC_STR_ERR_SET_AFRIKAANS,    
    SSC_STR_ERR_SET_ZULU,  
    SSC_STR_ERR_SET_LITHUANIAN, 
    SSC_STR_ERR_SET_LATVIAN,  
    SSC_STR_ERR_SET_ESTONIAN,  
    SSC_STR_ERR_SET_ARMENIAN,     
    SSC_STR_ERR_SET_ALBANIAN,
    SSC_STR_ERR_SET_GEORGIAN,    
    SSC_STR_ERR_SET_MOLDOVAN,
    SSC_STR_ERR_SET_KANNADA,
    SSC_STR_ERR_SET_MALAYALAM,
    SSC_STR_ERR_SET_LAO,
    SSC_STR_ERR_SET_KHMER,
    SSC_STR_ERR_SET_MYANMAR,
    SSC_STR_ERR_SET_GUJARATI,
    SSC_STR_ERR_SET_ORIYA,
    SSC_STR_ERR_SET_ZAWGYI,
    /* please add language ssc string definition above this line */
    SSC_SCR_ENGINEER_MODE_STR_ID,
    SSC_SCR_FACTORY_MODE_STR_ID,
    SSC_SCR_IMEI_CAPTION_ID,
    //SSC_SCR_SW_VERSION_CAPTION_ID,
    SSC_SCR_HW_VERSION_CAPTION_ID,
    //SSC_SCR_SERIAL_NUMBER_CAPTION_ID,
    SSC_STR_ERR_SET_DEFAULT,
    SSC_STR_ERR_SET_ENGLISH
} SSC_STR_ID_ENUM;

#endif /* __SSC_RES_DEF_H__ */

