#include "MMI_features.h"

<?xml version = "1.0" encoding = "UTF-8"?>

<APP id = "SRV_SOUNDEFFECT">

    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
#ifdef __MMI_AUDIO_EQUALIZER__
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET1"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET2"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET3"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET4"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET5"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET6"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET7"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_EQ_SET8"/>
#endif

#ifdef __MMI_AUDIO_REVERB_EFFECT__
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB_SET1"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB_SET2"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB_SET3"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB_SET4"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB_SET5"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_REVERB_SET6"/>
#endif

#ifdef __MMI_AUDIO_SURROUND_EFFECT__
    <STRING id="STR_ID_SRV_SOUND_EFFECT_SURROUND"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_SURROUND_MODE1"/>
    <STRING id="STR_ID_SRV_SOUND_EFFECT_SURROUND_MODE2"/>
#endif

</APP>

